cask_args appdir: "~/Applications", require_sha: true

brew 'chrome-cli'
brew 'fribidi'
brew 'gh'
brew 'go'
brew 'harfbuzz'
brew 'jesseduffield/lazygit/lazygit'
brew 'jq'
brew 'just'
brew 'libffi'
brew 'libmagic'
brew 'libxmlsec1'
brew 'neovim', args: ['HEAD']
brew 'node'
brew 'postgresql@14'
brew 'pre-commit'
brew 'rabbitmq'
brew 'redis'
brew 'ripgrep'
brew 'semgrep'
brew 'tldr'
brew 'tmux'
brew 'wget'

cask '1password'
cask 'cleanshot'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'karabiner-elements'
cask 'lunar'
cask 'maccy'
cask 'nikitabobko/tap/aerospace'
cask 'notunes'
cask 'raycast'
cask 'scroll-reverser'
cask 'visual-studio-code'
cask 'vlc'

# fonts
cask 'font-hack-nerd-font'
cask 'font-meslo-lg-nerd-font'

